import { readFile } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import assert from "node:assert/strict";
import { buildContentScript } from "../scripts/lib/content-build.mjs";

const repoRoot = path.resolve(import.meta.dirname, "..");

test("content script is generated from modular Hybrid, Fast, and Full sources", async () => {
  const generated = await buildContentScript(repoRoot, { write: false });
  const current = await readFile(path.join(repoRoot, "content.js"), "utf8");
  const debugModule = await readFile(path.join(repoRoot, "src", "content", "debug-log.js"), "utf8");
  const fastModule = await readFile(path.join(repoRoot, "src", "content", "capture-fast.js"), "utf8");
  const fullModule = await readFile(path.join(repoRoot, "src", "content", "capture-full.js"), "utf8");
  const background = await readFile(path.join(repoRoot, "background.js"), "utf8");
  const backendServer = await readFile(path.join(repoRoot, "tools", "advanced-pdf", "server.js"), "utf8");
  const backendRender = await readFile(path.join(repoRoot, "tools", "advanced-pdf", "render.js"), "utf8");
  const popupHtml = await readFile(path.join(repoRoot, "popup.html"), "utf8");
  const popupJs = await readFile(path.join(repoRoot, "popup.js"), "utf8");

  assert.equal(current.replace(/\r\n/g, "\n"), generated);
  assert.match(generated, /function createDebugLog/);
  assert.match(generated, /async function collectFastConversationMessages/);
  assert.match(generated, /\/api\/auth\/session/);
  assert.match(generated, /Bearer \$\{attempt\.accessToken\}/);
  assert.match(generated, /\/backend-api\/conversations\/\$\{encodedId\}/);
  assert.match(generated, /include_has_versions=true&num_turns=\$\{FAST_CONVERSATION_API_PAGE_SIZE\}/);
  assert.match(generated, /conversationApi\.pagination\.complete/);
  assert.match(generated, /pageUrl\.searchParams\.set\("before", cursor\)/);
  assert.match(generated, /getChatGptAccessTokenFromPageBootstrap/);
  assert.match(generated, /tree_format=true/);
  assert.match(generated, /routes\/_conversation\.g\.\$gizmoId\.c\.\$conversationId/);
  assert.match(generated, /function createMessageCollector/);
  assert.match(generated, /function enrichVisibleThinkingFlyouts/);
  assert.match(generated, /function settleVisibleThinkingFlyoutSnapshots/);
  assert.match(generated, /function extractThinkingFlyoutSources/);
  assert.match(generated, /function extractThinkingFlyoutStructuredMarkdown/);
  assert.match(generated, /function extractThinkingFlyoutStepEntries/);
  assert.match(generated, /function extractThinkingFlyoutCodeCard/);
  assert.match(generated, /renderThinkingFlyoutStructuredBlock/);
  assert.match(generated, /THINKING_FLYOUT_STEP_LABEL_RE/);
  assert.match(generated, /THINKING_FLYOUT_CODE_TITLE_RE/);
  assert.match(generated, /function collectThinkingCodeBlock/);
  assert.match(generated, /function isThinkingFlyoutStepHeadingSafe/);
  assert.match(generated, /function formatThinkingFlyoutContentLine/);
  assert.match(generated, /function formatThinkingFlyoutLinesAsMarkdown/);
  assert.match(generated, /items\.push\(`#### \$\{line\}/);
  assert.match(generated, /THINKING_FLYOUT_SOURCES_RE/);
  assert.match(generated, /THINKING_SOURCE_TRIGGER_RE/);
  assert.match(generated, /function isThinkingSourceTriggerElement/);
  assert.match(generated, /\.filter\(isThinkingPanelTriggerElement\)/);
  assert.match(generated, /element\.getAttribute\("aria-label"\) \|\| ""/);
  assert.match(generated, /element\.closest\("#chatgpt-exporter-selector-host, nav, header, aside, \[role='menu'\]"\)/);
  assert.match(generated, /screen-threadFlyOut/);
  assert.match(generated, /sourceCount: snapshot\.sources/);
  assert.match(generated, /async function collectHybridConversationMessages/);
  assert.match(generated, /function reconcileHybridMessages/);
  assert.match(generated, /hybridCapture\.reconciled/);
  assert.match(generated, /hybridCapture\.fullOnlyCandidates/);
  assert.match(generated, /function refreshPortableMessageImageStats/);
  assert.match(generated, /imagesDeferred/);
  assert.match(generated, /base64 embedding deferred until export/);
  assert.doesNotMatch(generated, /base64 embedding disabled during message scan/);
  assert.match(generated, /function dedupeMarkdownImageReferences/);
  assert.match(generated, /chatgpt-asset:/);
  assert.match(generated, /function stripMarkdownImagesFromLinkLabel/);
  assert.match(generated, /function isFaviconImageUrl/);
  assert.match(generated, /function isTimestampDividerText/);
  assert.match(generated, /option value="full" selected>Full \(Recommended\)/);
  assert.match(generated, /Hybrid \(Experimental for ImageGen\)/);
  assert.match(generated, /data-action="start-scan">Start Scan/);
  assert.match(generated, /Opening the selector does not scan/);
  const selectorOpen = generated.match(/open\(nextApi\)\s*\{[\s\S]*?return \{ ok: true, panelOpen: true \};\s*\}/)?.[0] || "";
  assert.ok(selectorOpen, "selector open method should be present");
  assert.doesNotMatch(selectorOpen, /startScan\(|\.loadMessages\(/);
  assert.match(generated, /function createCaptureJobManager/);
  assert.match(generated, /A stale capture job cannot replace the loaded snapshot/);
  assert.match(generated, /function buildCaptureCompletenessReport/);
  assert.match(generated, /data-option="allow-incomplete"/);
  assert.match(generated, /snapshot\.captureMode/);
  assert.match(generated, /modeSelect\.disabled = isBusy/);
  assert.doesNotMatch(generated, /function reloadMessages/);
  assert.doesNotMatch(generated, /data-action=['"]refresh['"]/);
  assert.doesNotMatch(generated, /Export Loaded Hybrid Bundle/);
  assert.match(generated, /Switch to Full mode if you want to scan the page/);
  assert.doesNotMatch(generated, /falling back to Full scan/);
  assert.match(generated, /assetEmbed\.start/);
  assert.match(generated, /assetEmbed\.domFallback/);
  assert.match(generated, /resolveMountedMessageNodeForPortableMessage/);
  assert.match(generated, /sediment/);
  assert.match(generated, /ADVANCED_PDF_IMAGE_EMBED_CONCURRENCY/);
  assert.match(debugModule, /function downloadDebugLog/);
  assert.match(fastModule, /function buildMessagesFromConversationApi/);
  assert.match(fastModule, /function getApiMessageStructuralSkipReason/);
  assert.match(fastModule, /asset_pointer/);
  assert.match(fastModule, /fastCapture\.thinkingMerged/);
  assert.match(fastModule, /removeApiPrivateUseArtifacts/);
  assert.match(fullModule, /async function hydrateVirtualizedTurns/);
  assert.match(background, /file-service/);
  assert.match(background, /sediment/);
  assert.match(background, /\/backend-api\/files\/\$\{encodedId\}\/content/);
  assert.match(background, /extractImageUrlsFromMetadata/);
  assert.match(backendServer, /captureMode: payload\.captureMode \|\| ""/);
  assert.match(backendServer, /CGCE_LOCAL_API_TOKEN/);
  assert.match(backendServer, /X-Convo-Vault-Token/);
  assert.match(backendServer, /X-Bundle-Timings/);
  assert.match(backendServer, /externalizeEmbeddedImageAssets/);
  assert.match(backendServer, /buildBundleAssetEntries/);
  assert.match(backendServer, /compactMarkdownSourceLinks/);
  assert.match(backendServer, /message\.counts\?\.images/);
  assert.match(backendServer, /language: payload\.language \|\| payload\.locale \|\| payload\.documentLanguage/);
  assert.match(backendServer, /language: payload\.language \|\| ""/);
  assert.match(backendServer, /buildOutputObjectIndex/);
  assert.match(backendServer, /outputObjects/);
  assert.match(backendServer, /degradedObjectCount/);
  assert.match(backendRender, /margin: 44px 34px/);
  assert.match(backendRender, /<html lang="\$\{escapeAttr\(documentLanguage\)\}">/);
  assert.match(backendRender, /normalizeDocumentLanguage/);
  assert.match(backendRender, /language: payload\.language \|\| payload\.locale \|\| payload\.documentLanguage/);
  assert.match(backendRender, /Noto Sans CJK JP/);
  assert.match(backendRender, /Noto Sans CJK KR/);
  assert.match(backendRender, /Noto Sans Arabic/);
  assert.match(backendRender, /Noto Sans Hebrew/);
  assert.match(backendRender, /dir="auto"/);
  assert.match(backendRender, /\.user-meta-row\s*{\s*display: inline-flex;/);
  assert.match(backendRender, /assistant-row/);
  assert.match(backendRender, /assistant-title/);
  assert.match(backendRender, /stripAttachmentOnlyLines/);
  assert.match(backendRender, /compactMarkdownSourceLinks/);
  assert.match(backendRender, /renderMermaidDiagram/);
  assert.match(backendRender, /parseMermaidFlowchart/);
  assert.match(backendRender, /parseMermaidSequence/);
  assert.match(backendRender, /parseMermaidErDiagram/);
  assert.match(backendRender, /parseMermaidStateDiagram/);
  assert.match(backendRender, /math_block/);
  assert.match(backendRender, /math-frac/);
  assert.match(backendRender, /renderChartBlock/);
  assert.match(backendRender, /chart-svg/);
  assert.match(backendRender, /remote-media-card/);
  assert.match(backendRender, /shouldShowCodeLabel/);
  assert.doesNotMatch(popupHtml, /portInput|cacheDirInput|browserPathInput|saveSettingsButton|resetSettingsButton/);
  assert.doesNotMatch(popupJs, /portInput|cacheDirInput|browserPathInput|saveSettingsButton|resetSettingsButton/);
  assert.doesNotMatch(popupJs, /--port|--cache-dir|--browser-path/);
  assert.match(popupJs, /CGCE_LOCAL_API_TOKEN/);
  assert.match(popupJs, /createLocalApiToken/);
  assert.doesNotMatch(generated, /@convo-vault-include/);
});
