import { readFile } from "node:fs/promises";
import path from "node:path";
import { test } from "node:test";
import assert from "node:assert/strict";
import { buildContentScript } from "../scripts/lib/content-build.mjs";

const repoRoot = path.resolve(import.meta.dirname, "..");

test("content script is generated from modular Hybrid, Fast, and Full sources", async () => {
  const generated = await buildContentScript(repoRoot, { write: false });
  const current = await readFile(path.join(repoRoot, "content.js"), "utf8");
  const debugModule = await readFile(path.join(repoRoot, "src", "content", "debug-log.js"), "utf8");
  const fastModule = await readFile(path.join(repoRoot, "src", "content", "capture-fast.js"), "utf8");
  const fullModule = await readFile(path.join(repoRoot, "src", "content", "capture-full.js"), "utf8");
  const background = await readFile(path.join(repoRoot, "background.js"), "utf8");
  const backendServer = await readFile(path.join(repoRoot, "tools", "advanced-pdf", "server.js"), "utf8");
  const backendRender = await readFile(path.join(repoRoot, "tools", "advanced-pdf", "render.js"), "utf8");
  const popupHtml = await readFile(path.join(repoRoot, "popup.html"), "utf8");
  const popupJs = await readFile(path.join(repoRoot, "popup.js"), "utf8");

  assert.equal(current.replace(/\r\n/g, "\n"), generated);
  assert.match(generated, /function createDebugLog/);
  assert.match(generated, /async function collectFastConversationMessages/);
  assert.match(generated, /\/api\/auth\/session/);
  assert.match(generated, /Bearer \$\{attempt\.accessToken\}/);
  assert.match(generated, /tree_format=true/);
  assert.match(generated, /routes\/_conversation\.g\.\$gizmoId\.c\.\$conversationId/);
  assert.match(generated, /function createMessageCollector/);
  assert.match(generated, /async function collectHybridConversationMessages/);
  assert.match(generated, /function reconcileHybridMessages/);
  assert.match(generated, /hybridCapture\.reconciled/);
  assert.match(generated, /hybridCapture\.fullOnlyCandidates/);
  assert.match(generated, /function refreshPortableMessageImageStats/);
  assert.match(generated, /function stripMarkdownImagesFromLinkLabel/);
  assert.match(generated, /function isFaviconImageUrl/);
  assert.match(generated, /function isTimestampDividerText/);
  assert.match(generated, /option value="hybrid" selected>Hybrid/);
  assert.match(generated, /Export Loaded Hybrid Bundle/);
  assert.match(generated, /Switch to Full mode if you want to scan the page/);
  assert.doesNotMatch(generated, /falling back to Full scan/);
  assert.match(generated, /assetEmbed\.start/);
  assert.match(generated, /assetEmbed\.domFallback/);
  assert.match(generated, /resolveMountedMessageNodeForPortableMessage/);
  assert.match(generated, /sediment/);
  assert.match(generated, /ADVANCED_PDF_IMAGE_EMBED_CONCURRENCY/);
  assert.match(debugModule, /function downloadDebugLog/);
  assert.match(fastModule, /function buildMessagesFromConversationApi/);
  assert.match(fastModule, /function getApiMessageStructuralSkipReason/);
  assert.match(fastModule, /asset_pointer/);
  assert.match(fastModule, /fastCapture\.thinkingMerged/);
  assert.match(fastModule, /removeApiPrivateUseArtifacts/);
  assert.match(fullModule, /async function hydrateVirtualizedTurns/);
  assert.match(background, /file-service/);
  assert.match(background, /sediment/);
  assert.match(background, /\/backend-api\/files\/\$\{encodedId\}\/content/);
  assert.match(background, /extractImageUrlsFromMetadata/);
  assert.match(backendServer, /captureMode: payload\.captureMode \|\| ""/);
  assert.match(backendServer, /CGCE_LOCAL_API_TOKEN/);
  assert.match(backendServer, /X-Convo-Vault-Token/);
  assert.match(backendServer, /X-Bundle-Timings/);
  assert.match(backendServer, /compactMarkdownSourceLinks/);
  assert.match(backendServer, /message\.counts\?\.images/);
  assert.match(backendRender, /margin: 44px 34px/);
  assert.match(backendRender, /assistant-title/);
  assert.match(backendRender, /stripAttachmentOnlyLines/);
  assert.match(backendRender, /compactMarkdownSourceLinks/);
  assert.match(backendRender, /renderMermaidDiagram/);
  assert.match(backendRender, /parseMermaidFlowchart/);
  assert.match(backendRender, /shouldShowCodeLabel/);
  assert.doesNotMatch(popupHtml, /portInput|cacheDirInput|browserPathInput|saveSettingsButton|resetSettingsButton/);
  assert.doesNotMatch(popupJs, /portInput|cacheDirInput|browserPathInput|saveSettingsButton|resetSettingsButton/);
  assert.doesNotMatch(popupJs, /--port|--cache-dir|--browser-path/);
  assert.match(popupJs, /CGCE_LOCAL_API_TOKEN/);
  assert.match(popupJs, /createLocalApiToken/);
  assert.doesNotMatch(generated, /@convo-vault-include/);
});
